---
# Playbook for workspace creation

- name: Create workspace {{ros_workspace}}
  file: state=directory path={{ros_workspace}}/src

- name: catkin_init_workspace
  shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && catkin_init_workspace"
    chdir={{ros_workspace}}/src
    creates={{ros_workspace}}/src/CMakeLists.txt

- name: Init workspace
  command: wstool init .
    chdir={{ros_workspace}}/src
    creates={{ros_workspace}}/src/.rosinstall

- name: Update dependencies
  shell: bash -c "rosdep update -y"
         chdir={{ros_workspace}}

- name: Adding roslint with python3 support
  blockinfile:
    path: {{ros_workspace}}/src/.rosinstall
    block: |
      - git:
        local-name: roslint
        uri: https://github.com/ros/roslint.git
        version: python3-support

- name: catkin_make for roslint
  shell: catkin_make
  args:
    chdir: {{ros_workspace}}
