---
# VSCode IDE installation

- name: Update package lists
  apt: update_cache=yes
  become: yes

- name: Download VSC .deb file
  get_url:
    url: https://go.microsoft.com/fwlink/?LinkID=760868
    dest: /tmp/code.deb

- name: Intall needed libs
  apt: 
    name: ['libxkbfile1','libsecret-1-0']
    install_recommends: no
    state: "present"
  become: yes

- name: Install VSC from .deb
  shell: dpkg -i /tmp/code.deb
  become: yes

- name: Remove VSC .deb file
  file:
    state: absent
    path: /tmp/code.deb
