---
# Playbook for repository installation check

- name: catkin clean workspace directories
  file: path={{item}} state=absent
  with_items:
    - "{{ros_workspace}}/build_isolated"
    - "{{ros_workspace}}/devel_isolated"
    - "{{ros_workspace}}/install_isolated"

- name: Set non-repository packages using lists substraction
  set_fact:
     non_repo_packages : "{{workspace_packages_names|difference(repo_packages_names)|join(';')}}"

- name: build workspace in isolation and install
  shell: bash -c "source <(grep '^export\|^source' {{ansible_env.HOME}}/.bashrc) && catkin_make_isolated --install --cmake-args -DBUILD_TESTING=0 -DCATKIN_SKIP_TESTING=1"
    chdir={{ros_workspace}}
  register: command_result
  failed_when: >
    (("'SyntaxError' in command_result.stderr") and (command_result.rc >= 1)) or 
    (("'failed' in command_result.stderr") and (command_result.rc >= 1))

- name: Check python files for import errors
  include_role: 
    names: ci/code_style_check/python
  vars:
    linter_command: pylint --disable=all --enable=E0611,E0401
