---

- name: Install pycurl
  apt: name=python-pycurl state=present

- name: Add PyCharm ppa
  become: yes
  apt_repository:
    repo: 'ppa:ubuntu-desktop/ubuntu-make'
    filename: 'ppa_ubuntu_desktop_ubuntu_make_trusty'
    mode: 664

- name: Update package lists
  apt: update_cache=yes

- name: Install ubuntu make
  become: yes
  apt: 
    name: ubuntu-make 
    state: present

- name: Change umake directory owner and group
  become: yes
  file: path=/usr/share/umake/ state=directory mode=0777 owner="{{ros_user}}" group="{{ros_group}}" recurse=true

- name: Install programming tools
  become: yes
  sudo_user: "{{ros_user}}"
  shell: bash -c "yes | umake ide pycharm /usr/share/umake/ide/pycharm"
  
- name: Change pycharm app location
  become: yes
  command: cp ~{{ros_user}}/.local/share/applications/jetbrains-pycharm-ce.desktop /usr/share/applications

- name: Set workspace for pycharm icon
  lineinfile: dest=/usr/share/applications/jetbrains-pycharm-ce.desktop regexp=^Exec= line="Exec="/usr/share/umake/ide/pycharm/bin/pycharm.sh" %F"

- name: Set favorite icons
  shell: dbus-launch --exit-with-session gsettings set com.canonical.Unity.Launcher favorites "['application://ubiquity.desktop', 'application://jetbrains-pycharm-ce.desktop', 'application://terminator.desktop', 'application://nautilus.desktop', 'application://firefox.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"
  sudo_user: "{{ros_user}}"
