---
# Playbook for Python code style check

- name: Get list of all Python files by extension in repository
  script: "../../common_resources/files/files_by_extension_and_policy.sh \
    {{repo_sources_path}} {{repo_sources_path}}/{{item.path}} py .lintignore"
  with_items: "{{repo_packages_list|default([])}}"
  register: python_files_with_extension

- name: Set variable to workaround ansible type evaluation issue
  set_fact:
    python_files_with_extension_results: "{{python_files_with_extension.results}}"

- name: Get list of all Python files by content in repository
  script: "../../common_resources/files/files_by_content_and_policy.sh \
    {{repo_sources_path}} {{repo_sources_path}}/{{item.path}} '^#!/usr/bin/env python|^#! /usr/bin/env python|^#!/usr/bin/python|^#! /usr/bin/python' .lintignore '.*\\..*'"
  with_items: "{{repo_packages_list|default([])}}"
  register: python_files_without_extension

- name: Set variable to workaround ansible type evaluation issue
  set_fact:
    python_files_without_extension_results: "{{python_files_without_extension.results}}"

- name: Execute roslint for every package and .py files and write results in unit tests format
  shell: |
    source /opt/ros/{{ros_release}}/setup.bash && rosrun roslint test_wrapper \
    {{ros_workspace}}/build/test_results/{{item.item.name}}/roslint-python-py-{{item.item.name}}.xml \
    'rosrun roslint pycodestyle --max-line-length=120 {{item.stdout}}'
     
    source /opt/ros/{{ros_release}}/setup.bash && rosrun roslint test_wrapper \
    {{ros_workspace}}/build/test_results/{{item.item.name}}/roslint-python3-py-{{item.item.name}}.xml \
    "pylint -sn --max-line-length=120 --disable=C0112,C0114,C0115,C0116,R0903,R0904,W9005,W9006,W9008,W9010,W9011,W9012,W9013,W9014,W9015,W9016,R0801,W0717,C1901,C2001,W0141,R0902,R0913,R0916,W0703,C0413,C0415,C0200,C0201,R1715,R1716,R1718 --msg-template='{abspath}:{line}:{column}:{msg_id}:{msg}' {{item.stdout}}"
  args:
    executable: "/bin/bash"
    chdir: "{{repo_sources_path}}/{{item.item.path}}"
  with_items: "{{python_files_with_extension_results|default([])}}"
  when: item.stdout != ""
  ignore_errors: True

- name: Execute roslint for every package and no extension files and write results in unit tests format
  shell: |
    source /opt/ros/{{ros_release}}/setup.bash && rosrun roslint test_wrapper \
    {{ros_workspace}}/build/test_results/{{item.item.name}}/roslint-python-ex-{{item.item.name}}.xml \
    'rosrun roslint pycodestyle --max-line-length=120 {{item.stdout}}'
         
    source /opt/ros/{{ros_release}}/setup.bash && rosrun roslint test_wrapper \
    {{ros_workspace}}/build/test_results/{{item.item.name}}/roslint-python3-ex-{{item.item.name}}.xml \
    "pylint -sn --max-line-length=120 --disable=C0112,C0114,C0115,C0116,R0903,R0904,W9005,W9006,W9008,W9010,W9011,W9012,W9013,W9014,W9015,W9016,R0801,W0717,C1901,C2001,W0141,R0902,R0913,R0916,W0703,C0413,C0415,C0200,C0201,R1715,R1716,R1718 --msg-template='{abspath}:{line}:{column}:{msg_id}:{msg}' {{item.stdout}}"
  args:
    executable: "/bin/bash"
    chdir: "{{repo_sources_path}}/{{item.item.path}}"
  with_items: "{{python_files_without_extension_results|default([])}}"
  when: item.stdout != ""
  ignore_errors: True


